# Generated by Django 6.0.3 on 2026-03-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='year',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='coordinators',
            field=models.ManyToManyField(related_name='events', to='sympo.coordinator'),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text='Event banner/poster', null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='prize_pool',
            field=models.CharField(blank=True, help_text='E.g., ₹2000 or First Prize: ₹1000', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Main Auditorium', max_length=150),
        ),
    ]
