# Generated by Django 6.0.3 on 2026-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympo', '0002_remove_event_coordinator_coordinator_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('poster', models.ImageField(blank=True, help_text='Workshop banner/poster', null=True, upload_to='workshops/')),
                ('guest_lecturer', models.CharField(help_text='Name and Designation of the Guest', max_length=150)),
                ('chairperson', models.CharField(help_text='Faculty Chairperson or main organizer', max_length=150)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(help_text='Format: HH:MM:SS')),
                ('end_time', models.TimeField(help_text='Format: HH:MM:SS')),
                ('venue', models.CharField(default='Main Auditorium', max_length=150)),
                ('registration_fee', models.CharField(blank=True, help_text='E.g., ₹200', max_length=100, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='registration_link',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sympo_registration_link',
            field=models.URLField(blank=True, help_text='Google Form URL for Symposium Events', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='workshop_registration_link',
            field=models.URLField(blank=True, help_text='Google Form URL for the Workshop', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check to make these the active links on the site'),
        ),
    ]
